baseURL: https://cuongvndev.github.io/
title: Cuong Vu
enableRobotsTXT: true
enableEmoji: true
theme: jane
hasCJKLanguage: false
paginate: 3
rssLimit: 20
disqusShortname: "cuongvndev"
googleAnalytics: "G-MPBTRXJEZK"
defaultContentLanguage: en
languages:
  en:
    languageCode: en
author:
  name: Cuong Vu
  url: /about
sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml
menu:
  main:
    - name: Home
      weight: 10
      identifier: home
      pageref: /
    - name: Archives
      weight: 20
      identifier: archives
      pageref: /post/
    - name: Tags
      weight: 30
      identifier: tags
      pageref: /tags/
    - name: Categories
      weight: 40
      identifier: categories
      pageref: /categories/
params:
  since: "2023"
  homeFullContent: false
  rssFullContent: true
  logoTitle: Cuong Vu
  moreMeta: true
  showMenuLanguageChooser: true
  keywords:
    - Hugo
    - theme
    - jane
  description: xxx.
  dateFormatToUse: 2006-01-02
  toc: true
  photoswipe: true
  customCSS: ['custom.css']
  customJS: []
  social:
    g-github: https://cuongvndev.github.io
  search:
    google:
      enable: true
      id: "c6448581e63304f73"
      title: "Search"