name: Auto Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          submodules: false  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          
    - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: 'latest'
            extended: true

    - name: Build
        run: hugo --minify    
        
        
    - name: Deploy to GitHub Pages
      run: |
        git config user.name "Cuong Vu"
        git config user.email "vucuong1112@gmail.com"
        git remote add www git@github.com:cuongvndev/cuongvndev.github.io.git
        git fetch www
        git checkout gh-pages
        git merge origin/gh-pages
        # Run any build commands here if needed
        git push www gh-pages:gh-pages
