name: push public source to cuongvndev blog

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Create SSH Key
        run: |
          mkdir ~/.ssh/
          cd ~/.ssh
          echo "$SSH_PRIVATE_KEY" > id_rsa
          pwd
          sudo chmod 600 id_rsa
          echo "$SSH_KNOWN_HOSTS" > known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.KNOWN_HOSTS}}
          # SSH_KEY_PATH: ${{ github.workspace }}/../private.key

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      
      - name: Deploy Files
        run: |
          git remote add www git@github.com:cuongvndev/cuongvndev.github.io.git
            git fetch www
            git push -u www gh-pages:master