name: push public source to cuongvndev blog

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push to another repo
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }} 
      with:
        source_file: ./public
        destination_repo: 'another_repo/release-test'
        user_email: 'vucuong1112@email.com'# your email
        user_name: 'cuongvndev'           # your login
        commit_message: 'update blog'